// frontend-svelte/src/lib/components/VideoTile.svelte
<!--
  VideoTile Component
  Displays a participant's video/audio with overlays for name, role, quality, and state.
-->

<script lang="ts">
  import type { Participant } from '../stores/room.svelte';

  let {
    participant,
    videoTrack = null,
    audioTrack = null,
    isActiveSpeaker = false,
    isLocal = false,
  }: {
    participant: Participant;
    videoTrack?: MediaStreamTrack | null;
    audioTrack?: MediaStreamTrack | null;
    isActiveSpeaker?: boolean;
    isLocal?: boolean;
  } = $props();

  let videoEl: HTMLVideoElement | undefined = $state();
  let audioEl: HTMLAudioElement | undefined = $state();

  // Bind video track to <video> element
  $effect(() => {
    if (videoEl) {
      if (videoTrack) {
        const stream = new MediaStream([videoTrack]);
        videoEl.srcObject = stream;
      } else {
        videoEl.srcObject = null;
      }
    }
  });

  // Bind audio track to <audio> element (not for local participant)
  $effect(() => {
    if (audioEl && !isLocal) {
      if (audioTrack) {
        const stream = new MediaStream([audioTrack]);
        audioEl.srcObject = stream;
      } else {
        audioEl.srcObject = null;
      }
    }
  });

  const qualityColor = $derived.by(() => {
    switch (participant.connectionQuality) {
      case 'good':
        return 'bg-green-400';
      case 'medium':
        return 'bg-yellow-400';
      case 'poor':
        return 'bg-red-400';
      default:
        return 'bg-gray-400';
    }
  });

  const roleBadge = $derived.by(() => {
    switch (participant.role) {
      case 'host':
        return 'Host';
      case 'co_host':
        return 'Co-Host';
      case 'moderator':
        return 'Mod';
      default:
        return null;
    }
  });
</script>

<div
  class="relative overflow-hidden rounded-lg bg-slate-800 {isActiveSpeaker
    ? 'ring-2 ring-brand-500 active-speaker'
    : 'ring-1 ring-slate-700'}"
>
  {#if videoTrack && participant.isVideoEnabled}
    <!-- svelte-ignore a11y_media_has_caption -->
    <video
      bind:this={videoEl}
      autoplay
      playsinline
      muted={isLocal}
      class="h-full w-full object-cover"
    ></video>
  {:else}
    <!-- No video - show avatar placeholder -->
    <div class="flex h-full w-full items-center justify-center bg-slate-800">
      <div
        class="flex h-16 w-16 items-center justify-center rounded-full bg-slate-600 text-2xl font-semibold text-slate-300"
      >
        {participant.displayName.charAt(0).toUpperCase()}
      </div>
    </div>
  {/if}

  <!-- Audio element for remote participants -->
  {#if audioTrack && !isLocal}
    <audio bind:this={audioEl} autoplay></audio>
  {/if}

  <!-- Bottom overlay: name + role -->
  <div
    class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent px-3 py-2"
  >
    <div class="flex items-center gap-2">
      <span class="text-sm font-medium text-white truncate">
        {participant.displayName}
        {#if isLocal}
          <span class="text-slate-400">(You)</span>
        {/if}
      </span>

      {#if roleBadge}
        <span
          class="rounded-full bg-brand-600 px-2 py-0.5 text-xs font-medium text-white"
        >
          {roleBadge}
        </span>
      {/if}
    </div>
  </div>

  <!-- Top-right: connection quality -->
  <div class="absolute right-2 top-2 flex items-center gap-1.5">
    <span class="h-2 w-2 rounded-full {qualityColor}" title="Connection: {participant.connectionQuality}"></span>
  </div>

  <!-- Top-left: muted / video-off indicators -->
  <div class="absolute left-2 top-2 flex items-center gap-1.5">
    {#if !participant.isAudioEnabled}
      <span
        class="flex h-6 w-6 items-center justify-center rounded-full bg-red-600/80"
        title="Muted"
      >
        <svg class="h-3.5 w-3.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M17 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2" />
        </svg>
      </span>
    {/if}

    {#if !participant.isVideoEnabled}
      <span
        class="flex h-6 w-6 items-center justify-center rounded-full bg-red-600/80"
        title="Camera off"
      >
        <svg class="h-3.5 w-3.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.536 8.464a5 5 0 010 7.072M12 9.5v5M18.364 5.636a9 9 0 010 12.728M3 3l18 18" />
        </svg>
      </span>
    {/if}
  </div>
</div>

// frontend/src/components/room/VideoTile.tsx
/**
 * VideoTile Component - Displays a participant's video stream
 *
 * Features:
 * - Video/Audio indicators
 * - Name overlay
 * - Connection quality indicator
 * - Spotlight/Pin functionality
 */

import { useRef, useEffect, useState } from 'react';
import { cn } from '../../utils/cn';
import {
  Mic,
  MicOff,
  VideoOff,
  Pin,
  MoreVertical,
  Wifi,
  WifiOff,
} from 'lucide-react';

interface VideoTileProps {
  stream: MediaStream | null;
  displayName: string;
  isLocal?: boolean;
  isMuted?: boolean;
  isVideoEnabled?: boolean;
  isScreenShare?: boolean;
  isSpotlighted?: boolean;
  connectionQuality?: 'good' | 'medium' | 'poor' | 'unknown';
  role?: string;
  onSpotlight?: () => void;
  onMute?: () => void;
  onKick?: () => void;
  className?: string;
}

export function VideoTile({
  stream,
  displayName,
  isLocal = false,
  isMuted = false,
  isVideoEnabled = true,
  isScreenShare = false,
  isSpotlighted = false,
  connectionQuality = 'unknown',
  role = 'viewer',
  onSpotlight,
  onMute,
  onKick,
  className,
}: VideoTileProps) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [isHovered, setIsHovered] = useState(false);
  const [audioLevel, setAudioLevel] = useState(0);

  // Attach stream to video element
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    if (stream) {
      video.srcObject = stream;
    } else {
      video.srcObject = null;
    }
  }, [stream]);

  // Audio level monitoring
  useEffect(() => {
    if (!stream || isMuted) {
      setAudioLevel(0);
      return;
    }

    const audioTrack = stream.getAudioTracks()[0];
    if (!audioTrack) return;

    const audioContext = new AudioContext();
    const analyser = audioContext.createAnalyser();
    const source = audioContext.createMediaStreamSource(stream);

    analyser.fftSize = 256;
    source.connect(analyser);

    const dataArray = new Uint8Array(analyser.frequencyBinCount);

    const updateLevel = () => {
      analyser.getByteFrequencyData(dataArray);
      const average = dataArray.reduce((a, b) => a + b, 0) / dataArray.length;
      setAudioLevel(average / 255);
    };

    const interval = setInterval(updateLevel, 100);

    return () => {
      clearInterval(interval);
      audioContext.close();
    };
  }, [stream, isMuted]);

  const connectionIcon = {
    good: <Wifi className="w-4 h-4 text-green-500" />,
    medium: <Wifi className="w-4 h-4 text-yellow-500" />,
    poor: <WifiOff className="w-4 h-4 text-red-500" />,
    unknown: null,
  };

  const roleColors = {
    host: 'bg-red-500',
    co_host: 'bg-orange-500',
    moderator: 'bg-blue-500',
    viewer: 'bg-gray-500',
  };

  return (
    <div
      className={cn(
        'relative rounded-lg overflow-hidden bg-gray-900',
        'aspect-video',
        isSpotlighted && 'ring-2 ring-yellow-500',
        audioLevel > 0.1 && 'ring-2 ring-green-500',
        className
      )}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {/* Video Element */}
      {isVideoEnabled && stream ? (
        <video
          ref={videoRef}
          autoPlay
          playsInline
          muted={isLocal}
          className={cn(
            'w-full h-full object-cover',
            isLocal && !isScreenShare && 'transform scale-x-[-1]'
          )}
        />
      ) : (
        <div className="w-full h-full flex items-center justify-center bg-gray-800">
          <div className="w-20 h-20 rounded-full bg-gray-700 flex items-center justify-center">
            <span className="text-2xl font-semibold text-white">
              {displayName.charAt(0).toUpperCase()}
            </span>
          </div>
        </div>
      )}

      {/* Audio Level Indicator */}
      {audioLevel > 0.05 && (
        <div
          className="absolute bottom-0 left-0 right-0 h-1 bg-green-500 transition-all"
          style={{ transform: `scaleX(${audioLevel})`, transformOrigin: 'left' }}
        />
      )}

      {/* Bottom Overlay */}
      <div className="absolute bottom-0 left-0 right-0 p-2 bg-gradient-to-t from-black/80 to-transparent">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            {/* Role Badge */}
            {role !== 'viewer' && (
              <span
                className={cn(
                  'px-2 py-0.5 text-xs rounded-full text-white',
                  roleColors[role as keyof typeof roleColors] || 'bg-gray-500'
                )}
              >
                {role.replace('_', '-')}
              </span>
            )}

            {/* Name */}
            <span className="text-white text-sm font-medium truncate max-w-[150px]">
              {displayName}
              {isLocal && ' (You)'}
            </span>
          </div>

          <div className="flex items-center gap-1">
            {/* Connection Quality */}
            {connectionIcon[connectionQuality]}

            {/* Audio Indicator */}
            {isMuted ? (
              <MicOff className="w-4 h-4 text-red-500" />
            ) : (
              <Mic className="w-4 h-4 text-white" />
            )}

            {/* Video Indicator */}
            {!isVideoEnabled && <VideoOff className="w-4 h-4 text-red-500" />}

            {/* Spotlight Indicator */}
            {isSpotlighted && <Pin className="w-4 h-4 text-yellow-500" />}
          </div>
        </div>
      </div>

      {/* Hover Controls */}
      {isHovered && !isLocal && (
        <div className="absolute top-2 right-2 flex gap-1">
          {onSpotlight && (
            <button
              onClick={onSpotlight}
              className={cn(
                'p-1.5 rounded-full bg-black/50 hover:bg-black/70 transition',
                isSpotlighted && 'bg-yellow-500/50'
              )}
              title="Spotlight"
            >
              <Pin className="w-4 h-4 text-white" />
            </button>
          )}

          {(onMute || onKick) && (
            <div className="relative group">
              <button
                className="p-1.5 rounded-full bg-black/50 hover:bg-black/70 transition"
                title="More options"
              >
                <MoreVertical className="w-4 h-4 text-white" />
              </button>

              {/* Dropdown Menu */}
              <div className="absolute right-0 top-full mt-1 hidden group-hover:block">
                <div className="bg-gray-800 rounded-lg shadow-lg py-1 min-w-[120px]">
                  {onMute && (
                    <button
                      onClick={onMute}
                      className="w-full px-3 py-2 text-left text-sm text-white hover:bg-gray-700 flex items-center gap-2"
                    >
                      <MicOff className="w-4 h-4" />
                      Mute
                    </button>
                  )}
                  {onKick && (
                    <button
                      onClick={onKick}
                      className="w-full px-3 py-2 text-left text-sm text-red-400 hover:bg-gray-700 flex items-center gap-2"
                    >
                      Remove
                    </button>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Screen Share Label */}
      {isScreenShare && (
        <div className="absolute top-2 left-2">
          <span className="px-2 py-1 bg-blue-500 text-white text-xs rounded-full">
            Screen
          </span>
        </div>
      )}
    </div>
  );
}
